blank_issues_enabled: false
contact_links:
  - name: ğŸš€ Feature Request
    url: https://github.com/org/repo/discussions
    about: test 2
  - name: â“ Support Questions
    url: https://github.com/org/repo/discussions
    about: test 1 
